services:
  - type: web
    name: segmentation-flask
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=1 --timeout=300 app.app:app
